###

GET http://localhost:3000/student

###

POST http://localhost:3000/student
Content-Type: application/json


{
    "name": "John33",
    "age": 230,
    "_id": "020130400202"
}

###

PUT http://localhost:3000/student

###

DELETE http://localhost:3000/student