###

GET http://localhost:3000/student?name=John33

###

POST http://localhost:3000/student
Content-Type: application/json


{
    "name": "John334",
    "age": 230,
    "_id": "0201130400202"
}

###

PUT http://localhost:3000/student/0201130400202
Content-Type:application/json

{
    "name":"John332"
}

###

DELETE http://localhost:3000/student